### PR TITLE
Update GettingStarted.md

### PR DESCRIPTION
**Pull request by juzhiyuan**
##### Checklist

- [x] `npm test` passes
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change
Fix typo in documentation.

- any feature?
No

### CODE REVIEW

**Comment by juzhiyuan** [comment]
I'm not sure what happened, but I modify it directly based on master branch.

**Comment by juzhiyuan** [comment]
@sorrycc Not sure what happened, I just changed 1 typo.

**Comment by juzhiyuan** [comment]
Any updates here?

**Comment by juzhiyuan** [comment]
cc @sorrycc

**Comment by juzhiyuan** [comment]
ping @yinheli

**Comment by yinheli** [comment]
> ping @yinheli

😂

**Pull request closed without merging**
